<?php declare(strict_types=1);

use Commerce365\CustomerPrice\ViewModel\CustomerPrice;
use Magento\Catalog\Block\Product\Price as ProductPrice;
use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;

/** @var ViewModelRegistry $viewModels */
/** @var Price $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */

/** @var ProductPrice $product */
$product = $block->getProduct();

/** @var CustomerPrice $customerPrice */
$customerPrice = $viewModels->require(CustomerPrice::class);
?>
<?php if ($customerPrice->isLoggedIn() && $customerPrice->isAjaxEnabled()): ?>
<script>
    (() => {
        const initFnName = 'initPrice<?= (int)$product->getId() ?>'
        if (window[initFnName]) {
            window[initFnName] = new Proxy(window[initFnName] , {
                apply(target, objContext, args) {
                    const instance = target.apply(objContext, args);
                    instance.eventListeners['@update-initial-price-<?= (int)$product->getId() ?>.window'] = function (event) {
                        this.initialFinalPrice = event.detail;
                    }
                    instance.eventListeners['@update-uom-price-<?= (int)$product->getId() ?>.window'] = function (event) {
                        this.pricePerUom = event.detail.pricePerUOM;
                        this.uom = event.detail.UOM;
                        if (this.pricePerUom === undefined || this.uom === undefined) {
                            return;
                        }
                        let priceUomElements = document.querySelectorAll('[id=price-per-uom-<?= (int)$product->getId() ?>]');
                        if (priceUomElements.length) {
                            priceUomElements.forEach(priceUomElement => {
                                priceUomElement.innerHTML = '(' + this.pricePerUom + '/' + this.uom + ')';
                            })
                        } else {
                            document.querySelectorAll('[id=product-price-<?= (int)$product->getId() ?>]').forEach(container => {
                                let priceUomElement = document.createElement('span');
                                priceUomElement.classList.add('commerce365-price-per-uom');
                                priceUomElement.setAttribute('id', 'price-per-uom-<?= (int)$product->getId() ?>');
                                priceUomElement.innerHTML = '(' + this.pricePerUom + '/' + this.uom + ')';
                                container.appendChild(priceUomElement);
                            });
                        }
                    }

                    instance.getFormattedFinalPrice = new Proxy(instance.getFormattedFinalPrice, {
                        apply(target, objContext, args) {
                            let tierFound = false;
                            if (window.customerpriceConfig.selectedTierPriceInfo && instance.qty > 1) {
                                window.customerpriceConfig.selectedTierPriceInfo.forEach(tierPrice => {
                                    if (instance.qty >= tierPrice.qty) {
                                        const detail = {pricePerUOM: tierPrice.additional.pricePerUOM, UOM: tierPrice.additional.UOM}
                                        window.dispatchEvent(new CustomEvent("update-uom-price-<?= (int)$product->getId() ?>", {detail: detail}));
                                        tierFound = true;
                                    }
                                });
                            }

                            if (!tierFound && window.uomDetail !== undefined) {
                                window.dispatchEvent(new CustomEvent("update-uom-price-<?= (int)$product->getId() ?>", window.uomDetail));
                            }

                            return target.apply(objContext, args);
                        }
                    })
                    return instance;
                }
            });
        }
    })()
</script>
    <?php if (isset($hyvaCsp) && method_exists($hyvaCsp, 'registerInlineScript')) $hyvaCsp->registerInlineScript(); ?>
<?php endif; ?>
